"""Reference helpers embedded into generated, standalone reproducers."""

import inspect


def double_reference_source(function):
    """Double-precision copy of a reference interpreter, returned as source text.

    Used by the oracle trust gate: chaotic programs (nonlinear feedback loops,
    e.g. carry = rowsum(cos(carry)) + carry) amplify arithmetic-order noise by
    orders of magnitude, so no real kernel can reproduce the fp32 reference
    within tolerance and every such program would be reported as a wrong_result
    without a compiler bug (MLIRSmith counts exactly this as wasted effort).
    The fp64 copy computes the ideal continuous semantics; op-level storage
    quantizations are removed, `.float()` becomes `.double()`, and only the
    final output cast stays so both copies round to the same storage dtype.
    """
    source = inspect.getsource(function)
    name = function.__name__
    source = source.replace(f'def {name}(', f'def {name}_double(', 1)
    source = source.replace(".to(getattr(torch, attrs.get('dtype', 'float32')))", '')
    source = source.replace(".to(getattr(torch, attrs['dtype'])).float()", '.double()')
    source = source.replace(".to(getattr(torch, attrs['dtype']))", '')
    source = source.replace('.float()', '.double()')
    return source


def _finite_compare(C, ref, check_signed_zero=False):
    """Check exceptional values before measuring finite numerical error.

    Reference results are rounded to the declared output storage dtype. Matching
    NaNs are allowed; a NaN/Inf introduced or lost by the kernel is not.
    """
    import torch
    if C.shape != ref.shape:
        raise RuntimeError(f"WRONG RESULT: shape {tuple(C.shape)} != {tuple(ref.shape)}")
    # Bound temporary memory for the very large shapes generated by the fuzzer.
    # Float64 differences avoid overflowing while subtracting finite fp32 values.
    actual = C.reshape(-1)
    expected = ref.reshape(-1)
    max_error = torch.zeros((), dtype=torch.float64, device=C.device)
    magnitude_sum = torch.zeros_like(max_error)
    finite_count = torch.zeros((), dtype=torch.int64, device=C.device)
    for start in range(0, actual.numel(), 1 << 20):
        c = actual[start:start + (1 << 20)].to(torch.float64)
        r = expected[start:start + (1 << 20)].to(dtype=C.dtype, device=C.device).to(torch.float64)
        if not torch.equal(torch.isnan(c), torch.isnan(r)):
            raise RuntimeError("WRONG RESULT: NaN locations differ")
        if not torch.equal(torch.isposinf(c), torch.isposinf(r)) or not torch.equal(torch.isneginf(c), torch.isneginf(r)):
            raise RuntimeError("WRONG RESULT: infinity locations or signs differ")
        if check_signed_zero:
            zeros = (c == 0) & (r == 0)
            if not torch.equal(torch.signbit(c[zeros]), torch.signbit(r[zeros])):
                raise RuntimeError("WRONG RESULT: signed zeros differ")
        mask = torch.isfinite(c) & torch.isfinite(r)
        max_error = torch.maximum(max_error, torch.where(mask, (c - r).abs(), 0.0).max())
        magnitude_sum += torch.where(mask, r.abs(), 0.0).sum()
        finite_count += mask.sum()
    count = finite_count.item()
    if count == 0:
        return 0.0, 1.0, 0.0
    max_diff = max_error.item()
    ref_norm = magnitude_sum.item() / count + 1e-6
    return max_diff, ref_norm, max_diff / ref_norm
