import triton
import triton.language as tl

import torch

import sys

torch.manual_seed(0)

def _finite_compare(C, ref, check_signed_zero=False):
    """Check exceptional values before measuring finite numerical error.

    Reference results are rounded to the declared output storage dtype. Matching
    NaNs are allowed; a NaN/Inf introduced or lost by the kernel is not.
    """
    import torch
    if C.shape != ref.shape:
        raise RuntimeError(f"WRONG RESULT: shape {tuple(C.shape)} != {tuple(ref.shape)}")
    # Bound temporary memory for the very large shapes generated by the fuzzer.
    # Float64 differences avoid overflowing while subtracting finite fp32 values.
    actual = C.reshape(-1)
    expected = ref.reshape(-1)
    max_error = torch.zeros((), dtype=torch.float64, device=C.device)
    magnitude_sum = torch.zeros_like(max_error)
    finite_count = torch.zeros((), dtype=torch.int64, device=C.device)
    for start in range(0, actual.numel(), 1 << 20):
        c = actual[start:start + (1 << 20)].to(torch.float64)
        r = expected[start:start + (1 << 20)].to(dtype=C.dtype, device=C.device).to(torch.float64)
        if not torch.equal(torch.isnan(c), torch.isnan(r)):
            raise RuntimeError("WRONG RESULT: NaN locations differ")
        if not torch.equal(torch.isposinf(c), torch.isposinf(r)) or not torch.equal(torch.isneginf(c), torch.isneginf(r)):
            raise RuntimeError("WRONG RESULT: infinity locations or signs differ")
        if check_signed_zero:
            zeros = (c == 0) & (r == 0)
            if not torch.equal(torch.signbit(c[zeros]), torch.signbit(r[zeros])):
                raise RuntimeError("WRONG RESULT: signed zeros differ")
        mask = torch.isfinite(c) & torch.isfinite(r)
        max_error = torch.maximum(max_error, torch.where(mask, (c - r).abs(), 0.0).max())
        magnitude_sum += torch.where(mask, r.abs(), 0.0).sum()
        finite_count += mask.sum()
    count = finite_count.item()
    if count == 0:
        return 0.0, 1.0, 0.0
    max_diff = max_error.item()
    ref_norm = magnitude_sum.item() / count + 1e-6
    return max_diff, ref_norm, max_diff / ref_norm


def matrix_layout(rows, cols, layout):
    """Return element strides, base offset and storage size including a guard."""
    if rows < 1 or cols < 1:
        raise ValueError('Matrix dimensions must be positive')
    if layout == 'contiguous':
        stride_row, stride_col, offset = cols, 1, 0
    elif layout == 'transposed':
        stride_row, stride_col, offset = 1, rows, 0
    elif layout == 'strided':
        stride_row, stride_col, offset = 2 * cols + 3, 2, 0
    elif layout == 'offset':
        stride_row, stride_col, offset = cols + 3, 1, 7
    elif layout == 'broadcast_rows':
        stride_row, stride_col, offset = 0, 1, 0
    elif layout == 'broadcast_cols':
        stride_row, stride_col, offset = 1, 0, 0
    else:
        raise ValueError('Unsupported matrix layout: ' + layout)
    size = offset + (rows - 1) * stride_row + (cols - 1) * stride_col + 17
    return stride_row, stride_col, offset, size


def _region_input(shape, dtype, pattern, scale, device='cuda'):
    import torch
    if dtype == torch.int8:
        # int8 has no randn; small signed integers keep every product and
        # partial sum far inside the int32 accumulator range.
        if pattern == 'alternating':
            phase = torch.randint(0, 4, (), device=device)
            value = ((torch.arange(shape[0] * shape[1], device=device) + phase) % 4 - 2).reshape(shape).to(torch.int8)
        else:
            value = torch.randint(-8, 8, shape, device=device).to(torch.int8)
        return (value * scale).to(torch.int8)
    if pattern == 'normal':
        value = torch.randn(shape, dtype=dtype, device=device)
    elif pattern == 'integer':
        value = torch.randint(-3, 4, shape, device=device).to(dtype)
    elif pattern == 'alternating':
        # Signed, exactly representable values exercise cancellation and zeros.
        phase = torch.randint(0, 4, (), device=device)
        value = ((torch.arange(shape[0] * shape[1], device=device) + phase) % 4 - 2).reshape(shape).to(dtype)
    else:
        raise ValueError('Unknown region input pattern: ' + pattern)
    return value * scale


def _region_input_storage(shape, dtype, pattern, scale, layout, device='cuda'):
    """Initialize unique addresses; retain padding for input-integrity checks."""
    import torch
    rows, cols = shape
    stride_row, stride_col, offset, size = matrix_layout(rows, cols, layout)
    storage = torch.full((size,), 19, dtype=dtype, device=device)
    view = storage.as_strided(shape, (stride_row, stride_col), offset)
    # Broadcast views overlap: never copy an entire matrix into those views.
    if layout == 'broadcast_rows':
        view[0].copy_(_region_input((1, cols), dtype, pattern, scale, device)[0])
    elif layout == 'broadcast_cols':
        view[:, 0].copy_(_region_input((rows, 1), dtype, pattern, scale, device)[:, 0])
    else:
        view.copy_(_region_input(shape, dtype, pattern, scale, device))
    return storage, view


def _region_equal(actual, expected, label):
    import torch
    if not torch.equal(actual.contiguous().view(torch.uint8), expected.contiguous().view(torch.uint8)):
        raise RuntimeError('WRONG RESULT: ' + label)


def _region_check(actual, expected, relative, tolerance, label):
    try:
        maximum, _, normalized = _finite_compare(actual, expected)
    except RuntimeError as error:
        raise RuntimeError(f'WRONG RESULT: {label}: {error}') from error
    error = normalized if relative else maximum
    if error > tolerance:
        raise RuntimeError(f'WRONG RESULT: {label}: error={error}, tolerance={tolerance}')


def _ulp_jitter(x):
    """One-ulp perturbation of a storage tensor.

    The smallest difference any two implementations can possibly disagree by:
    the kernel and the reference read the same storage values, but arithmetic
    order and precision differ. A reference that changes far beyond tolerance
    under this perturbation cannot be reproduced by any kernel, so the
    numeric check is meaningless for it (see _reference_stable).
    """
    import torch
    if not x.dtype.is_floating_point:
        return x.clone()
    y = x.clone()
    y[y == 0] = torch.finfo(x.dtype).tiny
    # nextafter has no Half overload in its CUDA kernel, so perturb on CPU
    # (all floating dtypes supported there) and move back to the input device.
    y_cpu = y.cpu()
    return torch.nextafter(y_cpu, y_cpu.sign()).to(x.dtype).to(x.device)


def _reference_stable(reference, double_reference, jitter_reference=None):
    """Oracle trust gate for the fp32 reference interpreter.

    The numeric check is only meaningful when the reference reproduces its own
    double-precision copy: chaotic recurrences amplify arithmetic-order noise
    by orders of magnitude, so a disagreement means *no* implementation could
    pass the check and the program must not be reported as a wrong_result.
    The fixed 1e-2 self-error threshold sits between benign fp32 noise
    (<= 1e-4 relative, including the one-ulp fp16 output-rounding boundary)
    and chaotic divergence (>= 1) by several orders of magnitude.

    jitter_reference, when given, is the reference recomputed on one-ulp
    perturbed inputs: it catches the milder, order-sensitive amplifiers whose
    own rounding stays stable but whose output depends on reduction order —
    again unpassable by any real kernel. Either disagreement fails the gate.
    """
    alternates = [double_reference]
    if jitter_reference is not None:
        alternates.append(jitter_reference)
    for alternate in alternates:
        try:
            _, _, self_relative = _finite_compare(reference, alternate)
        except RuntimeError:
            self_relative = float('inf')
        if self_relative > 1e-2:
            return False
    return True


def _run_region(launches, inputs, reference, repeats, tolerance, relative=False,
                variant_kinds=None, references=None, prepare_markers=None,
                reference_verify=None, reference_jitter=None):
    """Compile every variant concurrently, then execute them in order.

    The caller computes reference before any target kernel can corrupt inputs.
    Tile geometry stays fixed across schedules, preserving tile-local semantics.
    The schedule sweep variants (threads, num_stages, loop_kind) all share one
    reference because the reference interpreter is schedule-independent;
    variant_kinds names each variant in cross-variant invariance diagnostics
    and references (if given) supplies one reference per variant.

    prepare_markers carries the stderr marker each variant's own prepare
    closure prints (`prepare_{p_index}_{i}` under a layout sweep); a compile
    failure re-prints the failing variant's marker before re-raising so the
    last-marker location inference still names the crashing variant even
    though the compiles themselves ran concurrently.

    reference_verify, when given, is a zero-argument closure returning the
    double-precision copy of the reference; reference_jitter likewise returns
    the reference recomputed on one-ulp-jittered inputs. A structured-reference
    failure is first checked against _reference_stable: when the fp32 reference
    disagrees with either copy, the failure is oracle noise (a chaotic or
    reduction-order-sensitive program), re-raised as ORACLE UNSTABLE instead of
    a wrong_result.
    """
    import torch
    import sys
    # Cold kernel compilation is the dominant harness cost (nvcc subprocesses,
    # CPU-bound; the GPU is idle until the first launch), so every variant is
    # compiled up front on at most this many threads instead of paying each
    # compile serially right before its execution. Execution below keeps the
    # historical serial order. This literal is self-contained: no module-level
    # name travels into the standalone reproducer. Kept in sync with
    # EXTENDED_COMPILE_THREADS in backends/common/knobs.py.
    compile_threads = 8
    if repeats < 1 or not launches:
        raise ValueError('Region execution requires a launch and positive repeats')
    if variant_kinds is None:
        variant_kinds = ['schedule'] * len(launches)
    if references is None:
        references = [reference] * len(launches)
    if prepare_markers is None:
        prepare_markers = [f'prepare_{variant}' for variant in range(len(launches))]
    if len(variant_kinds) != len(launches) or len(references) != len(launches) or len(prepare_markers) != len(launches):
        raise ValueError('Region variant metadata must match the launch count')
    guard = 16
    output = torch.full((reference.numel() + 2 * guard,), 23,
                        dtype=reference.dtype, device=reference.device)
    actual = output[guard:-guard].view_as(reference)
    snapshots = [tensor.clone() for tensor in inputs]
    baseline = None
    # Integer outputs (int8 GEMM -> int32 C) cannot hold NaN poison.
    floating = reference.dtype.is_floating_point
    prepared = [None] * len(launches)
    errors = [None] * len(launches)
    if len(launches) == 1:
        try:
            prepared[0] = launches[0]()
        except BaseException as error:
            errors[0] = error
    else:
        import threading
        def compile_variant(start):
            # Strided worker: with more variants than threads, one thread
            # compiles every compile_threads-th variant so no variant is
            # left for the (serialized) execution phase.
            for variant in range(start, len(launches), compile_threads):
                try:
                    prepared[variant] = launches[variant]()
                except BaseException as error:
                    errors[variant] = error
        threads = [threading.Thread(target=compile_variant, args=(start,))
                   for start in range(min(len(launches), compile_threads))]
        for thread in threads:
            thread.start()
        for thread in threads:
            thread.join()
    for variant, launch in enumerate(prepared):
        if errors[variant] is not None:
            # Re-print the marker now: concurrent compiles interleave their
            # prepare markers, so the last one printed may not be the variant
            # that failed. Raising in variant order keeps the first-failure
            # contract of the historical serial loop.
            print(f'TILESMITH_STAGE={prepare_markers[variant]}', file=sys.stderr, flush=True)
            raise errors[variant]
        # stderr-only marker so a crash traceback names the failing variant
        # (location-aware root causes); the 'ALL PASSED' stdout line is untouched.
        print(f'TILESMITH_STAGE=execute_variant_{variant}', file=sys.stderr, flush=True)
        expected = references[variant]
        reference_nan = torch.isnan(expected) if floating else None
        for repeat in range(repeats):
            output.fill_(23)
            if floating:
                # Missing writes must fail even if the expected value itself is NaN.
                actual.fill_(float('nan'))
                actual.masked_fill_(reference_nan, 0.0)
            launch(actual)
            if reference.is_cuda:
                torch.cuda.synchronize(reference.device)
            if not torch.all(output[:guard] == 23) or not torch.all(output[-guard:] == 23):
                raise RuntimeError(f'WRONG RESULT: output canary modified (schedule={variant})')
            for tensor, snapshot in zip(inputs, snapshots):
                _region_equal(tensor, snapshot, 'input storage modified')
            if repeat == 0:
                if baseline is None:
                    baseline = actual.clone()
                    repeat_baseline = baseline
                else:
                    _region_check(actual, baseline, relative, tolerance,
                                  f'{variant_kinds[variant]} invariance')
                    repeat_baseline = actual.clone()
            else:
                _region_equal(actual, repeat_baseline, 'repeat determinism')
            try:
                _region_check(actual, expected, relative, tolerance, 'structured reference')
            except RuntimeError:
                # Suppress the chain: the chained WRONG RESULT text would leak
                # into stderr and skew root-cause classification.
                if reference_verify is not None and not _reference_stable(
                        expected, reference_verify(),
                        reference_jitter() if reference_jitter is not None else None):
                    raise RuntimeError('ORACLE UNSTABLE: reference disagrees with its '
                                       'fp64 or one-ulp-jittered copy; numeric check skipped') from None
                raise


def _typed_region_reference(A, B, body, block_m, block_n, output_dtype, functions=()):
    import torch
    m, n = A.shape[0], B.shape[1] if body['operations'][0]['kind'] == 'gemm' else A.shape[1]
    tm, tn = (m + block_m - 1) // block_m, (n + block_n - 1) // block_n
    by = torch.arange(tm, device=A.device)[:, None, None, None]
    bx = torch.arange(tn, device=A.device)[None, :, None, None]
    pool = {fn['name']: fn['body'] for fn in functions}
    memory = {}

    def tiles(x):
        x = torch.nn.functional.pad(x, (0, tn * block_n - n, 0, tm * block_m - m))
        return x.reshape(tm, block_m, tn, block_n).permute(0, 2, 1, 3)

    def index(axis, iteration):
        return {'row': by, 'column': bx, 'checkerboard': by + bx, 'iteration': iteration}[axis]

    def read_input(attrs):
        source = A if attrs['source'] == 'A' else B
        rows = by * block_m + torch.arange(block_m, device=A.device)[None, None, :, None] + attrs.get('row_offset', 0)
        cols = bx * block_n + torch.arange(block_n, device=A.device)[None, None, None, :] + attrs.get('col_offset', 0)
        valid = (rows < source.shape[0]) & (cols < source.shape[1])
        data = source[rows.clamp_max(source.shape[0] - 1), cols.clamp_max(source.shape[1] - 1)]
        return torch.where(valid, data, 0).to(getattr(torch, attrs.get('dtype', 'float32')))

    def execute(region, inherited, scope, argument=None, iteration=0, active=True):
        values = dict(inherited)
        if region['arguments']:
            values[region['arguments'][0]] = argument
        for op in region['operations']:
            kind, attrs = op['kind'], op['attrs']
            args = [values[v] for v in op['operands']]
            if kind == 'load':
                result = tiles(A.float())
            elif kind == 'gemm':
                result = tiles(A.float() @ B.float())
            elif kind == 'load_input':
                result = read_input(attrs)
            elif kind == 'store_tile':
                slot = (scope, op['result'])
                old = memory.get(slot, torch.zeros_like(args[0]))
                memory[slot] = torch.where(torch.as_tensor(active, device=A.device), args[0], old)
                result = slot
            elif kind == 'write_tile':
                memory[args[0]] = torch.where(torch.as_tensor(active, device=A.device), args[1], memory[args[0]])
                result = args[0]
            elif kind == 'load_tile':
                result = memory[args[0]].clone()
            elif kind == 'call':
                callee = pool[attrs['callee']]
                bindings = dict(zip(callee['arguments'], args))
                result = execute({**callee, 'arguments': []}, bindings, attrs['callee'], iteration=iteration, active=active)
            elif kind == 'if':
                condition = index(attrs.get('predicate', 'row'), iteration) % attrs.get('modulus', 2) == attrs['parity']
                condition = torch.as_tensor(condition, device=A.device)
                left = execute(op['regions'][0], values, scope, args[0], iteration, active & condition)
                right = execute(op['regions'][1], values, scope, args[0], iteration, active & ~condition)
                result = torch.where(condition, left, right)
            elif kind == 'for':
                result = args[0]
                for i in range(attrs['trip_count']):
                    result = execute(op['regions'][0], values, scope, result,
                                     attrs.get('start', 0) + i * attrs.get('step', 1), active)
            elif kind == 'cast':
                result = args[0].to(getattr(torch, attrs['dtype']))
            elif kind in ('broadcast_tile', 'to_tile'):
                result = args[0].expand(tm, tn, block_m, block_n)
                if kind == 'to_tile':
                    result = result.float()
            elif kind == 'reduce_tile':
                fn = {'sum': 'sum', 'max': 'amax', 'min': 'amin'}[attrs['reduction']]
                result = getattr(args[0].float(), fn)(attrs['axis'] + 2, keepdim=True)
            elif kind == 'tile_transpose':
                result = args[0].transpose(-1, -2)
            elif kind.startswith('row_'):
                x = args[0].float()
                if kind == 'row_softmax':
                    result = x.softmax(-1)
                else:
                    fn = {'row_sum': 'sum', 'row_max': 'amax', 'row_min': 'amin'}[kind]
                    result = getattr(x, fn)(-1, keepdim=True).expand_as(x)
            else:
                # Half arithmetic has an explicit rounding point at every SSA
                # definition; this is independent of the backend expression text.
                x = args[0].float()
                y = args[1].float() if len(args) > 1 else None
                if kind == 'scale': result = x * attrs['alpha']
                elif kind == 'neg': result = -x
                elif kind == 'abs': result = x.abs()
                elif kind == 'sqrt': result = x.abs().sqrt()
                elif kind == 'round': result = x.to(getattr(torch, attrs['dtype'])).float()
                elif kind == 'copy': result = x.clone()
                elif kind == 'exp': result = x.clamp(-10, 10).exp()
                elif kind == 'tanh': result = x.tanh()
                elif kind == 'erf': result = torch.erf(x)
                elif kind == 'log': result = x.abs().clamp_min(1e-3).log()
                elif kind == 'log2': result = x.abs().clamp_min(1e-3).log2()
                elif kind == 'exp2': result = x.clamp(-10, 10).exp2()
                elif kind == 'rsqrt': result = x.abs().clamp_min(1e-6).rsqrt()
                elif kind == 'sin': result = x.sin()
                elif kind == 'cos': result = x.cos()
                elif kind == 'floor': result = x.floor()
                elif kind == 'ceil': result = x.ceil()
                elif kind == 'add': result = x + y
                elif kind == 'mul': result = x * y
                elif kind == 'sub': result = x - y
                elif kind == 'maximum': result = torch.maximum(x, y)
                elif kind == 'minimum': result = torch.minimum(x, y)
                elif kind == 'div': result = x / y.abs().clamp_min(0.001)
                elif kind == 'where': result = torch.where(x > 0, y, args[2].float())
                elif kind == 'index_add': result = x + index(attrs['axis'], iteration) * attrs['scale']
                else: raise ValueError('Unknown typed operation: ' + kind)
                result = result.to(args[0].dtype)
            values[op['result']] = result
        return values[region['yield_value']]

    output = execute(body, {}, 'main')
    return output.permute(0, 2, 1, 3).reshape(tm * block_m, tn * block_n)[:m, :n].to(getattr(torch, output_dtype))


def _prepare_typed_launch(kernel, inputs, layouts):
    """Allocate per-block scratch and check every block's guards after a launch."""
    import torch
    scratch = [torch.full((blocks, elements + 32), 23, device=inputs[0].device, dtype=getattr(torch, dtype))
               for blocks, elements, dtype in layouts]
    def launch(output):
        # Poison contents each time: no dependency on a prior kernel invocation.
        for storage in scratch:
            storage.fill_(23)
            storage[:, 16:-16].fill_(float('nan'))
        kernel(*inputs, *(s.reshape(-1) for s in scratch), output)
        for storage in scratch:
            if not torch.all(storage[:, :16] == 23) or not torch.all(storage[:, -16:] == 23):
                raise RuntimeError('WRONG RESULT: scratch canary modified')
    return launch


def _typed_region_reference_double(A, B, body, block_m, block_n, output_dtype, functions=()):
    import torch
    m, n = A.shape[0], B.shape[1] if body['operations'][0]['kind'] == 'gemm' else A.shape[1]
    tm, tn = (m + block_m - 1) // block_m, (n + block_n - 1) // block_n
    by = torch.arange(tm, device=A.device)[:, None, None, None]
    bx = torch.arange(tn, device=A.device)[None, :, None, None]
    pool = {fn['name']: fn['body'] for fn in functions}
    memory = {}

    def tiles(x):
        x = torch.nn.functional.pad(x, (0, tn * block_n - n, 0, tm * block_m - m))
        return x.reshape(tm, block_m, tn, block_n).permute(0, 2, 1, 3)

    def index(axis, iteration):
        return {'row': by, 'column': bx, 'checkerboard': by + bx, 'iteration': iteration}[axis]

    def read_input(attrs):
        source = A if attrs['source'] == 'A' else B
        rows = by * block_m + torch.arange(block_m, device=A.device)[None, None, :, None] + attrs.get('row_offset', 0)
        cols = bx * block_n + torch.arange(block_n, device=A.device)[None, None, None, :] + attrs.get('col_offset', 0)
        valid = (rows < source.shape[0]) & (cols < source.shape[1])
        data = source[rows.clamp_max(source.shape[0] - 1), cols.clamp_max(source.shape[1] - 1)]
        return torch.where(valid, data, 0)

    def execute(region, inherited, scope, argument=None, iteration=0, active=True):
        values = dict(inherited)
        if region['arguments']:
            values[region['arguments'][0]] = argument
        for op in region['operations']:
            kind, attrs = op['kind'], op['attrs']
            args = [values[v] for v in op['operands']]
            if kind == 'load':
                result = tiles(A.double())
            elif kind == 'gemm':
                result = tiles(A.double() @ B.double())
            elif kind == 'load_input':
                result = read_input(attrs)
            elif kind == 'store_tile':
                slot = (scope, op['result'])
                old = memory.get(slot, torch.zeros_like(args[0]))
                memory[slot] = torch.where(torch.as_tensor(active, device=A.device), args[0], old)
                result = slot
            elif kind == 'write_tile':
                memory[args[0]] = torch.where(torch.as_tensor(active, device=A.device), args[1], memory[args[0]])
                result = args[0]
            elif kind == 'load_tile':
                result = memory[args[0]].clone()
            elif kind == 'call':
                callee = pool[attrs['callee']]
                bindings = dict(zip(callee['arguments'], args))
                result = execute({**callee, 'arguments': []}, bindings, attrs['callee'], iteration=iteration, active=active)
            elif kind == 'if':
                condition = index(attrs.get('predicate', 'row'), iteration) % attrs.get('modulus', 2) == attrs['parity']
                condition = torch.as_tensor(condition, device=A.device)
                left = execute(op['regions'][0], values, scope, args[0], iteration, active & condition)
                right = execute(op['regions'][1], values, scope, args[0], iteration, active & ~condition)
                result = torch.where(condition, left, right)
            elif kind == 'for':
                result = args[0]
                for i in range(attrs['trip_count']):
                    result = execute(op['regions'][0], values, scope, result,
                                     attrs.get('start', 0) + i * attrs.get('step', 1), active)
            elif kind == 'cast':
                result = args[0]
            elif kind in ('broadcast_tile', 'to_tile'):
                result = args[0].expand(tm, tn, block_m, block_n)
                if kind == 'to_tile':
                    result = result.double()
            elif kind == 'reduce_tile':
                fn = {'sum': 'sum', 'max': 'amax', 'min': 'amin'}[attrs['reduction']]
                result = getattr(args[0].double(), fn)(attrs['axis'] + 2, keepdim=True)
            elif kind == 'tile_transpose':
                result = args[0].transpose(-1, -2)
            elif kind.startswith('row_'):
                x = args[0].double()
                if kind == 'row_softmax':
                    result = x.softmax(-1)
                else:
                    fn = {'row_sum': 'sum', 'row_max': 'amax', 'row_min': 'amin'}[kind]
                    result = getattr(x, fn)(-1, keepdim=True).expand_as(x)
            else:
                # Half arithmetic has an explicit rounding point at every SSA
                # definition; this is independent of the backend expression text.
                x = args[0].double()
                y = args[1].double() if len(args) > 1 else None
                if kind == 'scale': result = x * attrs['alpha']
                elif kind == 'neg': result = -x
                elif kind == 'abs': result = x.abs()
                elif kind == 'sqrt': result = x.abs().sqrt()
                elif kind == 'round': result = x.double()
                elif kind == 'copy': result = x.clone()
                elif kind == 'exp': result = x.clamp(-10, 10).exp()
                elif kind == 'tanh': result = x.tanh()
                elif kind == 'erf': result = torch.erf(x)
                elif kind == 'log': result = x.abs().clamp_min(1e-3).log()
                elif kind == 'log2': result = x.abs().clamp_min(1e-3).log2()
                elif kind == 'exp2': result = x.clamp(-10, 10).exp2()
                elif kind == 'rsqrt': result = x.abs().clamp_min(1e-6).rsqrt()
                elif kind == 'sin': result = x.sin()
                elif kind == 'cos': result = x.cos()
                elif kind == 'floor': result = x.floor()
                elif kind == 'ceil': result = x.ceil()
                elif kind == 'add': result = x + y
                elif kind == 'mul': result = x * y
                elif kind == 'sub': result = x - y
                elif kind == 'maximum': result = torch.maximum(x, y)
                elif kind == 'minimum': result = torch.minimum(x, y)
                elif kind == 'div': result = x / y.abs().clamp_min(0.001)
                elif kind == 'where': result = torch.where(x > 0, y, args[2].double())
                elif kind == 'index_add': result = x + index(attrs['axis'], iteration) * attrs['scale']
                else: raise ValueError('Unknown typed operation: ' + kind)
                result = result.to(args[0].dtype)
            values[op['result']] = result
        return values[region['yield_value']]

    output = execute(body, {}, 'main')
    return output.permute(0, 2, 1, 3).reshape(tm * block_m, tn * block_n)[:m, :n].to(getattr(torch, output_dtype))


@triton.jit
def fn_0_v0(arg0, arg1, arg2, A, B, by, bx, iv):
    v1 = (tl.max(arg0.to(tl.float32), 0, keep_dims=True)).to(tl.float32)
    v2 = (tl.broadcast_to(v1, (128, 128))).to(tl.float32)
    v3 = (tl.ceil(v2.to(tl.float32))).to(tl.float32)
    v4 = (tl.trans(v3)).to(tl.float32)
    v5 = (tl.abs(v3.to(tl.float32))).to(tl.float32)
    v6 = (tl.broadcast_to(v5, (128, 128))).to(tl.float32)
    return v6
@triton.jit
def typed_kernel_0(A, B, C):
    by = tl.program_id(0)
    bx = tl.program_id(1)
    rows = by * 128 + tl.arange(0, 128)
    cols = bx * 128 + tl.arange(0, 128)
    v1 = tl.full((128, 128), 0, tl.float32)
    for ki in range(363):
        ks = ki * 32 + tl.arange(0, 32)
        aa = tl.load(A + 0 + rows[:, None]*11616 + ks[None, :]*1, (rows[:, None] < 4694) & (ks[None, :] < 11616), other=0)
        bb = tl.load(B + 0 + ks[:, None]*8249 + cols[None, :]*1, (ks[:, None] < 11616) & (cols[None, :] < 8249), other=0)
        v1 = tl.dot(aa, bb, v1)
    v2 = (v1.to(tl.float32)).to(tl.float32)
    v3 = (v2.to(tl.float32) + v2.to(tl.float32)).to(tl.float32)
    v4 = (v3.to(tl.float32) * 2.433131934776318).to(tl.float32)
    v5 = (v4.to(tl.float32) - v2.to(tl.float32)).to(tl.float32)
    v6 = (v5.to(tl.float32)).to(tl.float32)
    v7 = (v6.to(tl.float32)).to(tl.float32)
    if bx % 3 == 1:
        v8 = v7
        v9 = (tl.min(v8.to(tl.float32), 0, keep_dims=True)).to(tl.float32)
        v10 = (tl.broadcast_to(v9, (128, 128))).to(tl.float32)
        v11 = (tl.broadcast_to(v10, (128, 128))).to(tl.float32)
        v13 = v11
    else:
        v12 = v7
        v13 = v12
    v14 = (tl.broadcast_to(v13, (128, 128))).to(tl.float32)
    v15 = fn_0_v0(v14, v2, v1, A, B, by, bx, 0)
    tl.store(C + rows[:, None]*8249 + cols[None, :], v15, (rows[:, None] < 4694) & (cols[None, :] < 8249))

def prepare_0(A, B):
    kernel = lambda A, B, C: typed_kernel_0[(37, 65)](A, B, C, num_warps=4, enable_fp_fusion=False)
    return _prepare_typed_launch(kernel, (A, B), [])

@triton.jit
def fn_0_v1(arg0, arg1, arg2, A, B, by, bx, iv):
    v1 = (tl.max(arg0.to(tl.float32), 0, keep_dims=True)).to(tl.float32)
    v2 = (tl.broadcast_to(v1, (128, 128))).to(tl.float32)
    v3 = (tl.ceil(v2.to(tl.float32))).to(tl.float32)
    v4 = (tl.trans(v3)).to(tl.float32)
    v5 = (tl.abs(v3.to(tl.float32))).to(tl.float32)
    v6 = (tl.broadcast_to(v5, (128, 128))).to(tl.float32)
    return v6
@triton.jit
def typed_kernel_1(A, B, C):
    by = tl.program_id(0)
    bx = tl.program_id(1)
    rows = by * 128 + tl.arange(0, 128)
    cols = bx * 128 + tl.arange(0, 128)
    v1 = tl.full((128, 128), 0, tl.float32)
    for ki in range(363):
        ks = ki * 32 + tl.arange(0, 32)
        aa = tl.load(A + 0 + rows[:, None]*11616 + ks[None, :]*1, (rows[:, None] < 4694) & (ks[None, :] < 11616), other=0)
        bb = tl.load(B + 0 + ks[:, None]*8249 + cols[None, :]*1, (ks[:, None] < 11616) & (cols[None, :] < 8249), other=0)
        v1 = tl.dot(aa, bb, v1)
    v2 = (v1.to(tl.float32)).to(tl.float32)
    v3 = (v2.to(tl.float32) + v2.to(tl.float32)).to(tl.float32)
    v4 = (v3.to(tl.float32) * 2.433131934776318).to(tl.float32)
    v5 = (v4.to(tl.float32) - v2.to(tl.float32)).to(tl.float32)
    v6 = (v5.to(tl.float32)).to(tl.float32)
    v7 = (v6.to(tl.float32)).to(tl.float32)
    if bx % 3 == 1:
        v8 = v7
        v9 = (tl.min(v8.to(tl.float32), 0, keep_dims=True)).to(tl.float32)
        v10 = (tl.broadcast_to(v9, (128, 128))).to(tl.float32)
        v11 = (tl.broadcast_to(v10, (128, 128))).to(tl.float32)
        v13 = v11
    else:
        v12 = v7
        v13 = v12
    v14 = (tl.broadcast_to(v13, (128, 128))).to(tl.float32)
    v15 = fn_0_v1(v14, v2, v1, A, B, by, bx, 0)
    tl.store(C + rows[:, None]*8249 + cols[None, :], v15, (rows[:, None] < 4694) & (cols[None, :] < 8249))

def prepare_1(A, B):
    kernel = lambda A, B, C: typed_kernel_1[(37, 65)](A, B, C, num_warps=8, enable_fp_fusion=False)
    return _prepare_typed_launch(kernel, (A, B), [])

@triton.jit
def fn_0_v2(arg0, arg1, arg2, A, B, by, bx, iv):
    v1 = (tl.max(arg0.to(tl.float32), 0, keep_dims=True)).to(tl.float32)
    v2 = (tl.broadcast_to(v1, (128, 128))).to(tl.float32)
    v3 = (tl.ceil(v2.to(tl.float32))).to(tl.float32)
    v4 = (tl.trans(v3)).to(tl.float32)
    v5 = (tl.abs(v3.to(tl.float32))).to(tl.float32)
    v6 = (tl.broadcast_to(v5, (128, 128))).to(tl.float32)
    return v6
@triton.jit
def typed_kernel_2(A, B, C):
    by = tl.program_id(0)
    bx = tl.program_id(1)
    rows = by * 128 + tl.arange(0, 128)
    cols = bx * 128 + tl.arange(0, 128)
    v1 = tl.full((128, 128), 0, tl.float32)
    for ki in range(363):
        ks = ki * 32 + tl.arange(0, 32)
        aa = tl.load(A + 0 + rows[:, None]*11616 + ks[None, :]*1, (rows[:, None] < 4694) & (ks[None, :] < 11616), other=0)
        bb = tl.load(B + 0 + ks[:, None]*8249 + cols[None, :]*1, (ks[:, None] < 11616) & (cols[None, :] < 8249), other=0)
        v1 = tl.dot(aa, bb, v1)
    v2 = (v1.to(tl.float32)).to(tl.float32)
    v3 = (v2.to(tl.float32) + v2.to(tl.float32)).to(tl.float32)
    v4 = (v3.to(tl.float32) * 2.433131934776318).to(tl.float32)
    v5 = (v4.to(tl.float32) - v2.to(tl.float32)).to(tl.float32)
    v6 = (v5.to(tl.float32)).to(tl.float32)
    v7 = (v6.to(tl.float32)).to(tl.float32)
    if bx % 3 == 1:
        v8 = v7
        v9 = (tl.min(v8.to(tl.float32), 0, keep_dims=True)).to(tl.float32)
        v10 = (tl.broadcast_to(v9, (128, 128))).to(tl.float32)
        v11 = (tl.broadcast_to(v10, (128, 128))).to(tl.float32)
        v13 = v11
    else:
        v12 = v7
        v13 = v12
    v14 = (tl.broadcast_to(v13, (128, 128))).to(tl.float32)
    v15 = fn_0_v2(v14, v2, v1, A, B, by, bx, 0)
    tl.store(C + rows[:, None]*8249 + cols[None, :], v15, (rows[:, None] < 4694) & (cols[None, :] < 8249))

def prepare_2(A, B):
    kernel = lambda A, B, C: typed_kernel_2[(37, 65)](A, B, C, num_warps=4, enable_fp_fusion=True)
    return _prepare_typed_launch(kernel, (A, B), [])


def test_kernel_0():
    for input_case in range(2):
        torch.manual_seed(0 + input_case)
        a_storage, A = _region_input_storage((4694, 11616), torch.float16, 'normal', 0.1, 'contiguous')
        b_storage, B = _region_input_storage((11616, 8249), torch.float16, 'normal', 0.1, 'contiguous')
        def run_variant_0():
            print('TILESMITH_STAGE=prepare_0', file=sys.stderr, flush=True)
            return prepare_0(A, B)
        def run_variant_1():
            print('TILESMITH_STAGE=prepare_1', file=sys.stderr, flush=True)
            return prepare_1(A, B)
        def run_variant_2():
            print('TILESMITH_STAGE=prepare_2', file=sys.stderr, flush=True)
            return prepare_2(A, B)
        print('TILESMITH_STAGE=reference', file=sys.stderr, flush=True)
        ref = _typed_region_reference(A, B, {'arguments': [], 'operations': [{'kind': 'gemm', 'result': 'v1', 'operands': [], 'attrs': {}, 'regions': []}, {'kind': 'copy', 'result': 'v2', 'operands': ['v1'], 'attrs': {}, 'regions': []}, {'kind': 'add', 'result': 'v3', 'operands': ['v2', 'v2'], 'attrs': {}, 'regions': []}, {'kind': 'scale', 'result': 'v4', 'operands': ['v3'], 'attrs': {'alpha': 2.433131934776318}, 'regions': []}, {'kind': 'sub', 'result': 'v5', 'operands': ['v4', 'v2'], 'attrs': {}, 'regions': []}, {'kind': 'copy', 'result': 'v6', 'operands': ['v5'], 'attrs': {}, 'regions': []}, {'kind': 'cast', 'result': 'v7', 'operands': ['v6'], 'attrs': {'dtype': 'float32'}, 'regions': []}, {'kind': 'if', 'result': 'v13', 'operands': ['v7'], 'attrs': {'predicate': 'column', 'modulus': 3, 'parity': 1}, 'regions': [{'arguments': ['v8'], 'operations': [{'kind': 'reduce_tile', 'result': 'v9', 'operands': ['v8'], 'attrs': {'axis': 0, 'reduction': 'min'}, 'regions': []}, {'kind': 'broadcast_tile', 'result': 'v10', 'operands': ['v9'], 'attrs': {}, 'regions': []}, {'kind': 'to_tile', 'result': 'v11', 'operands': ['v10'], 'attrs': {}, 'regions': []}], 'yield_value': 'v11'}, {'arguments': ['v12'], 'operations': [], 'yield_value': 'v12'}]}, {'kind': 'to_tile', 'result': 'v14', 'operands': ['v13'], 'attrs': {}, 'regions': []}, {'kind': 'call', 'result': 'v15', 'operands': ['v14', 'v2', 'v1'], 'attrs': {'callee': 'fn_0'}, 'regions': []}], 'yield_value': 'v15'}, 128, 128, 'float16', [{'name': 'fn_0', 'body': {'arguments': ['arg0', 'arg1', 'arg2'], 'operations': [{'kind': 'reduce_tile', 'result': 'v1', 'operands': ['arg0'], 'attrs': {'axis': 0, 'reduction': 'max'}, 'regions': []}, {'kind': 'broadcast_tile', 'result': 'v2', 'operands': ['v1'], 'attrs': {}, 'regions': []}, {'kind': 'ceil', 'result': 'v3', 'operands': ['v2'], 'attrs': {}, 'regions': []}, {'kind': 'tile_transpose', 'result': 'v4', 'operands': ['v3'], 'attrs': {}, 'regions': []}, {'kind': 'abs', 'result': 'v5', 'operands': ['v3'], 'attrs': {}, 'regions': []}, {'kind': 'to_tile', 'result': 'v6', 'operands': ['v5'], 'attrs': {}, 'regions': []}], 'yield_value': 'v6'}}])
        _run_region([run_variant_0, run_variant_1, run_variant_2], (a_storage, b_storage), ref, 3, 0.1, relative=True, variant_kinds=['schedule', 'schedule', 'pass-config'], reference_verify=lambda: _typed_region_reference_double(A, B, {'arguments': [], 'operations': [{'kind': 'gemm', 'result': 'v1', 'operands': [], 'attrs': {}, 'regions': []}, {'kind': 'copy', 'result': 'v2', 'operands': ['v1'], 'attrs': {}, 'regions': []}, {'kind': 'add', 'result': 'v3', 'operands': ['v2', 'v2'], 'attrs': {}, 'regions': []}, {'kind': 'scale', 'result': 'v4', 'operands': ['v3'], 'attrs': {'alpha': 2.433131934776318}, 'regions': []}, {'kind': 'sub', 'result': 'v5', 'operands': ['v4', 'v2'], 'attrs': {}, 'regions': []}, {'kind': 'copy', 'result': 'v6', 'operands': ['v5'], 'attrs': {}, 'regions': []}, {'kind': 'cast', 'result': 'v7', 'operands': ['v6'], 'attrs': {'dtype': 'float32'}, 'regions': []}, {'kind': 'if', 'result': 'v13', 'operands': ['v7'], 'attrs': {'predicate': 'column', 'modulus': 3, 'parity': 1}, 'regions': [{'arguments': ['v8'], 'operations': [{'kind': 'reduce_tile', 'result': 'v9', 'operands': ['v8'], 'attrs': {'axis': 0, 'reduction': 'min'}, 'regions': []}, {'kind': 'broadcast_tile', 'result': 'v10', 'operands': ['v9'], 'attrs': {}, 'regions': []}, {'kind': 'to_tile', 'result': 'v11', 'operands': ['v10'], 'attrs': {}, 'regions': []}], 'yield_value': 'v11'}, {'arguments': ['v12'], 'operations': [], 'yield_value': 'v12'}]}, {'kind': 'to_tile', 'result': 'v14', 'operands': ['v13'], 'attrs': {}, 'regions': []}, {'kind': 'call', 'result': 'v15', 'operands': ['v14', 'v2', 'v1'], 'attrs': {'callee': 'fn_0'}, 'regions': []}], 'yield_value': 'v15'}, 128, 128, 'float16', [{'name': 'fn_0', 'body': {'arguments': ['arg0', 'arg1', 'arg2'], 'operations': [{'kind': 'reduce_tile', 'result': 'v1', 'operands': ['arg0'], 'attrs': {'axis': 0, 'reduction': 'max'}, 'regions': []}, {'kind': 'broadcast_tile', 'result': 'v2', 'operands': ['v1'], 'attrs': {}, 'regions': []}, {'kind': 'ceil', 'result': 'v3', 'operands': ['v2'], 'attrs': {}, 'regions': []}, {'kind': 'tile_transpose', 'result': 'v4', 'operands': ['v3'], 'attrs': {}, 'regions': []}, {'kind': 'abs', 'result': 'v5', 'operands': ['v3'], 'attrs': {}, 'regions': []}, {'kind': 'to_tile', 'result': 'v6', 'operands': ['v5'], 'attrs': {}, 'regions': []}], 'yield_value': 'v6'}}]), reference_jitter=lambda: _typed_region_reference(_ulp_jitter(A), _ulp_jitter(B), {'arguments': [], 'operations': [{'kind': 'gemm', 'result': 'v1', 'operands': [], 'attrs': {}, 'regions': []}, {'kind': 'copy', 'result': 'v2', 'operands': ['v1'], 'attrs': {}, 'regions': []}, {'kind': 'add', 'result': 'v3', 'operands': ['v2', 'v2'], 'attrs': {}, 'regions': []}, {'kind': 'scale', 'result': 'v4', 'operands': ['v3'], 'attrs': {'alpha': 2.433131934776318}, 'regions': []}, {'kind': 'sub', 'result': 'v5', 'operands': ['v4', 'v2'], 'attrs': {}, 'regions': []}, {'kind': 'copy', 'result': 'v6', 'operands': ['v5'], 'attrs': {}, 'regions': []}, {'kind': 'cast', 'result': 'v7', 'operands': ['v6'], 'attrs': {'dtype': 'float32'}, 'regions': []}, {'kind': 'if', 'result': 'v13', 'operands': ['v7'], 'attrs': {'predicate': 'column', 'modulus': 3, 'parity': 1}, 'regions': [{'arguments': ['v8'], 'operations': [{'kind': 'reduce_tile', 'result': 'v9', 'operands': ['v8'], 'attrs': {'axis': 0, 'reduction': 'min'}, 'regions': []}, {'kind': 'broadcast_tile', 'result': 'v10', 'operands': ['v9'], 'attrs': {}, 'regions': []}, {'kind': 'to_tile', 'result': 'v11', 'operands': ['v10'], 'attrs': {}, 'regions': []}], 'yield_value': 'v11'}, {'arguments': ['v12'], 'operations': [], 'yield_value': 'v12'}]}, {'kind': 'to_tile', 'result': 'v14', 'operands': ['v13'], 'attrs': {}, 'regions': []}, {'kind': 'call', 'result': 'v15', 'operands': ['v14', 'v2', 'v1'], 'attrs': {'callee': 'fn_0'}, 'regions': []}], 'yield_value': 'v15'}, 128, 128, 'float16', [{'name': 'fn_0', 'body': {'arguments': ['arg0', 'arg1', 'arg2'], 'operations': [{'kind': 'reduce_tile', 'result': 'v1', 'operands': ['arg0'], 'attrs': {'axis': 0, 'reduction': 'max'}, 'regions': []}, {'kind': 'broadcast_tile', 'result': 'v2', 'operands': ['v1'], 'attrs': {}, 'regions': []}, {'kind': 'ceil', 'result': 'v3', 'operands': ['v2'], 'attrs': {}, 'regions': []}, {'kind': 'tile_transpose', 'result': 'v4', 'operands': ['v3'], 'attrs': {}, 'regions': []}, {'kind': 'abs', 'result': 'v5', 'operands': ['v3'], 'attrs': {}, 'regions': []}, {'kind': 'to_tile', 'result': 'v6', 'operands': ['v5'], 'attrs': {}, 'regions': []}], 'yield_value': 'v6'}}]))

if __name__ == '__main__':
    test_kernel_0()
    print('ALL PASSED')
